version: '3.4'

services:
    project1:
        image: ${DOCKER_REGISTRY-}project1
        build:
          context: .
          dockerfile: Project1\Dockerfile
        depends_on:
            - sqldata

    project2:
        image: ${DOCKER_REGISTRY-}project2
        build:
          context: .
          dockerfile: Project2\Dockerfile
        depends_on:
            - sqldata
            - project1

    sqldata:
        image: microsoft/mssql-server-windows-express
        environment:
          - SA_PASSWORD=Contrader2020
          - ACCEPT_EULA=Y
        ports:
          - "5434:1433"