apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: project1
  name: project1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    io.kompose.service: project1
